### ISSUE TITLE
302 / 404 status codes

### ISSUE THREAD

**Issue by maps82** [cereallarceny/cra-ssr#11]
Thanks for this great boilerplate project. I'm wondering how to deliver a real 404 http status code if the page is not found or 302 on a react-router redirect.

Is this possible?

**Comment by linonetwo** [comment]
Why not a 404 Page? It would be better for SEO.

**Comment by maps82** [comment]
Yes, a 404 page but together with a 404 status instead of 200.

**Comment by cereallarceny** [comment]
Is there a particular reason you need to return the 404 status code?  Most progressive web applications will still return a 200 with a 404 "page".  This is certainly what React Router does (because it's not a server, and therefore can't return a response).  If you want a server to return a response, you're more than welcome to modify the code in `server.js`, listen for whatever routes are incorrect, and then return the appropriate response code.  Alternatively, you can just [implement a catch-all route](https://github.com/ReactTraining/react-router/issues/5081#issuecomment-299728209) in React Router like most people do and call it a day.

I'm closing this as it doesn't seem to have anything to do with cra-ssr.

**Comment by nsatija** [comment]
Can we open this again. GWT is complaining that page looks like 404 but is return 200 on several pages. Next.js allows it like this https://github.com/zeit/next.js/issues/746

**Comment by marinav** [comment]
I don't know if it's a bad practise or not but I solved the problem using staticContext. 
My NotFound component looks like this : 

```
import React from 'react';

export default ({ staticContext = {}, history }) => {
  if (staticContext) {
    staticContext.status = 404;
  }
  return (
  <p>404</p>
  );
};
```

And I just added at the end of the loader.js file :

`res.status(context.status || 200).send(html)`

Now 404 are in 404 status. I hope this could help someone.

**Comment by nsatija** [comment]
@marinav Thank you for your input on this. I am trying to figure out how to address my use case with your suggestion above. So I have lets say 7000 product detail pages index by google. but lets say one product no longer exists so google when crawls my product detail page www.yyy.com/product-details/<productid> then in the frontload section I make an api call to see if product still exists, if not I want to send back 404 status to google, if i redirect it to a not found page.. google sees that as a 301.. I think with the above solution I could just render that component on product detail page yeah?
