### ISSUE TITLE
I think your demo site is not working properly

### ISSUE THREAD

**Issue by markky21** [cereallarceny/cra-ssr#3]
I downloaded your repository and launched the application and what comes from the server has an empty html skeleton. I thing it should have not empty #root div at least. The same on the website: https://cra-ssr.herokuapp.com/.

**Comment by cereallarceny** [comment]
Do you have Javascript enabled?  I'm able to load the entire website.
<img width="614" alt="screen shot 2018-02-02 at 1 25 37 pm" src="https://user-images.githubusercontent.com/1297930/35733165-97834208-081c-11e8-87e4-a51d73fa74c2.png">

**Comment by markky21** [comment]
<img width="1627" alt="screen shot 2018-02-04 at 10 07 16" src="https://user-images.githubusercontent.com/25418142/35775943-7a92a4ae-0993-11e8-8d85-afafb6e82a30.png">
No, it's not that :) div # root that comes from the server is empty. I think it should not be like this. div # root should contain the rendered html. Unless it was not your goal. Thx for quick answer!

**Comment by chuck-durst** [comment]
Hi,

Same problem here after having cloned your repo and also in your heroku app.

When looking at the title tag of your HTML markup (from the Chrome dev tools), I have "React App" instead of "Homepage | SSR Website".

Btw everything seems to work just fine when making a test with the Facebook debug tool, I just don't understand how it is actually possible ?

I'm gonna make some tests with a personal project to see if it works too. Thank you for the great work anyway! :)

**Comment by cereallarceny** [comment]
I now use the following library for server-side rendering: https://github.com/kirill-konshin/create-react-server/

I'll likely make a Medium post on this shortly and deprecate this library.

**Comment by shashircciit** [comment]
@cereallarceny  hey I am also getting the same issue like @markky21. If you have any solution kindly share with me.
