### ISSUE TITLE
SSR render async Helmet content using redux-saga?

### ISSUE THREAD

**Issue by francisrod01** [cereallarceny/cra-ssr#35]
I'm trying to build an app where needs to get data before send props to `<Helmet>` but I don't know if it's possible because I don't see nothing like it in the docs.

I'm also using `redux-saga` just like that: #34

And there's no possible to show this content in Helmet component. The content is always `empty`

```js
<Page {...this.props.client.info.SEO}>
    {this.props.client.info ? <show content here> : <Loading />}
</Page>
```

I'll let the helmet issue here: https://github.com/nfl/react-helmet/issues/409

Stackoverflow question:

https://stackoverflow.com/questions/52768134/ssr-with-helmet-also-render-async-meta-and-content

**Comment by cereallarceny** [comment]
Hey, my apologies for the long wait @francisrod01 - I'm looking to ensure this is fixed with version 2.0.  If you're interested, I could really use your thoughts for what you'd like to see in the upcoming version.  Feel free to [comment on the issue here](https://github.com/cereallarceny/cra-ssr/issues/61) with any suggestions.  :)

**Comment by francisrod01** [comment]
Of course! I'd like to help!
I'll fork and try to do something cool for the next version

**Comment by cereallarceny** [comment]
Hey, unfortunately I've deprecated the project after finding out about
Razzle.
