### ISSUE TITLE
Question: How can we prevent page flash?

### ISSUE THREAD

**Issue by harrison0723** [cereallarceny/cra-ssr#42]
Since we're not rendering styles at server, page 'flashes' with barebone HTML upon load until styles are fetched later on. How can we make the loading experience better?

1. Load CSS at server?
2. Some logic at client that triggers when css chunks are loaded?

Open to other ideas too.

**Comment by harrison0723** [comment]
Currently my hack is to add a `display: none` style class (from the first loaded CSS chunk) to my 'flashing` components. It has managed to hide those barebone HTML fast enough. I guess it's good enough to get around the issue, but it loses the point of having fast rendering with server side.

**Comment by aartrost** [comment]
Hi! 

After a frustrating 2 days of debugging I FINALLY figured this one out. Turns out the problem was two-fold, making it all the more annoying to debug. Anyways, heres the PR I created: https://github.com/cereallarceny/cra-ssr/pull/43. Apply these changes and re-build your app and all should be well.

**Comment by cereallarceny** [comment]
Closed by #43
